'use client'
import { useEffect, useMemo, useState } from 'react'
import type { Session } from '@supabase/supabase-js'
import { Upload, Landmark, Fuel, Flame, Search, CheckCircle2, AlertTriangle, XCircle, Pencil, FileSpreadsheet, Download, Printer, Database, LayoutDashboard, RefreshCw, LogOut, Plus, LoaderCircle, Trash2, RotateCcw, ClipboardPaste } from 'lucide-react'
import { AppData, BankTx, UnitType } from '@/lib/types'
import { classify, fmtDate, inDateRange, parseBank, parsePastedBank, parsePastedRedemptions, parsePastedSettlements, parseRedemptions, parseSettlements, rupiah, toCSV } from '@/lib/utils'
import { supabase, supabaseConfigured } from '@/lib/supabase'
import { addUnit, bootstrapUnits, createBatch, deleteBankData, deleteRedemptionData, deleteSettlementData, insertBank, insertRedemptions, insertSettlements, loadUnitData, resetUnitData, RkUnit, updateInternalNote } from '@/lib/db'

const initial:AppData={bank:[],settlements:[],redemptions:[],unitType:'SPBU',unitName:'SPBU Utama'}
const statusLabel:any={matched:'Cocok',partial:'Ada selisih',review:'Perlu cek',unmatched:'Belum cocok'}
const months=['Januari','Februari','Maret','April','Mei','Juni','Juli','Agustus','September','Oktober','November','Desember']

export default function Home(){
 const [session,setSession]=useState<Session|null>(null),[authLoading,setAuthLoading]=useState(true)
 const [units,setUnits]=useState<RkUnit[]>([]),[activeUnit,setActiveUnit]=useState<RkUnit|null>(null)
 const [data,setData]=useState<AppData>(initial), [tab,setTab]=useState('dashboard'), [query,setQuery]=useState(''), [editing,setEditing]=useState<BankTx|null>(null)
 const [busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[replaceBank,setReplaceBank]=useState(true)
 const [dateFrom,setDateFrom]=useState(''),[dateTo,setDateTo]=useState('')
 const today=new Date()
 const [pasteKind,setPasteKind]=useState<'bank'|'settlement'|'redemption'|null>(null),[pasteText,setPasteText]=useState(''),[pastePreview,setPastePreview]=useState<any>(null)
 const [pasteMonth,setPasteMonth]=useState(today.getMonth()+1),[pasteYear,setPasteYear]=useState(today.getFullYear()),[replacePaste,setReplacePaste]=useState(false)

 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setAuthLoading(false)});const {data:s}=supabase.auth.onAuthStateChange((_e,sess)=>{setSession(sess);setAuthLoading(false)});return()=>s.subscription.unsubscribe()},[])
 useEffect(()=>{if(!session)return; (async()=>{try{setBusy(true);const u=await bootstrapUnits();setUnits(u);setActiveUnit(x=>x&&u.find(z=>z.id===x.id)||u[0]||null)}catch(e:any){setNotice(e.message||'Gagal memuat unit')}finally{setBusy(false)}})()},[session])
 useEffect(()=>{if(!activeUnit)return;(async()=>{try{setBusy(true);const d=await loadUnitData(activeUnit.id);setData({...d,unitId:activeUnit.id,unitType:activeUnit.unitType,unitName:activeUnit.name})}catch(e:any){setNotice(e.message||'Gagal memuat data')}finally{setBusy(false)}})()},[activeUnit])

 const analyzed=useMemo(()=>classify(data.bank,data.settlements,data.redemptions),[data.bank,data.settlements,data.redemptions])
 const ranged=useMemo(()=>analyzed.filter(x=>inDateRange(x.date,dateFrom,dateTo)),[analyzed,dateFrom,dateTo])
 const filtered=ranged.filter(x=>(x.description+' '+x.internalNote+' '+x.category).toLowerCase().includes(query.toLowerCase()))
 const rangedSettlements=useMemo(()=>data.settlements.filter(x=>inDateRange(x.date,dateFrom,dateTo)),[data.settlements,dateFrom,dateTo])
 const rangedRedemptions=useMemo(()=>data.redemptions.filter(x=>inDateRange(x.date,dateFrom,dateTo)),[data.redemptions,dateFrom,dateTo])
 const counts={matched:ranged.filter(x=>x.matchStatus==='matched').length, review:ranged.filter(x=>x.matchStatus==='review'||x.matchStatus==='partial').length, unmatched:ranged.filter(x=>x.matchStatus==='unmatched').length}
 const incoming=ranged.reduce((a,b)=>a+b.credit,0), outgoing=ranged.reduce((a,b)=>a+b.debit,0)

 const reload=async()=>{if(!activeUnit)return;const d=await loadUnitData(activeUnit.id);setData({...d,unitId:activeUnit.id,unitType:activeUnit.unitType,unitName:activeUnit.name})}
 const handle=async(kind:'bank'|'settlement'|'redemption',f?:File)=>{if(!f||!activeUnit)return;try{setBusy(true);setNotice(`Membaca ${f.name}...`);if(kind==='bank'){const rows=await parseBank(f);if(!rows.length){setNotice('0 baris terbaca. Data lama tidak diubah. Format file perlu diperiksa.');return}if(replaceBank)await deleteBankData(activeUnit.id);const b=await createBatch(activeUnit.id,kind,f,rows.length);await insertBank(activeUnit.id,b,rows);setNotice(`${rows.length} baris rekening koran diproses${replaceBank?' dan menggantikan data rekening sebelumnya':''}.`)}if(kind==='settlement'){const rows=await parseSettlements(f);if(!rows.length){setNotice('0 baris setoran terbaca. File tidak disimpan.');return}const b=await createBatch(activeUnit.id,kind,f,rows.length);await insertSettlements(activeUnit.id,b,rows);setNotice(`${rows.length} baris setoran disimpan.`)}if(kind==='redemption'){const rows=await parseRedemptions(f);if(!rows.length){setNotice('0 baris tebusan terbaca. File tidak disimpan.');return}const b=await createBatch(activeUnit.id,kind,f,rows.length);await insertRedemptions(activeUnit.id,b,rows);setNotice(`${rows.length} baris tebusan disimpan.`)}await reload()}catch(e:any){setNotice('Gagal upload: '+(e.message||e))}finally{setBusy(false)}}
 const clearBank=async()=>{if(!activeUnit||!data.bank.length)return;const ok=window.confirm(`Hapus seluruh ${data.bank.length} transaksi rekening koran pada ${activeUnit.name}? Data setoran dan tebusan tidak ikut dihapus.`);if(!ok)return;try{setBusy(true);await deleteBankData(activeUnit.id);await reload();setNotice('Data rekening koran unit ini sudah dihapus.')}catch(e:any){setNotice('Gagal menghapus rekening koran: '+(e.message||e))}finally{setBusy(false)}}
 const clearSetoran=async()=>{if(!activeUnit||!data.settlements.length)return;const ok=window.confirm(`Hapus seluruh ${data.settlements.length} data setoran pada ${activeUnit.name}?`);if(!ok)return;try{setBusy(true);await deleteSettlementData(activeUnit.id);await reload();setNotice('Data setoran sudah dihapus.')}catch(e:any){setNotice('Gagal menghapus setoran: '+(e.message||e))}finally{setBusy(false)}}
 const clearTebusan=async()=>{if(!activeUnit||!data.redemptions.length)return;const ok=window.confirm(`Hapus seluruh ${data.redemptions.length} data tebusan pada ${activeUnit.name}?`);if(!ok)return;try{setBusy(true);await deleteRedemptionData(activeUnit.id);await reload();setNotice('Data tebusan sudah dihapus.')}catch(e:any){setNotice('Gagal menghapus tebusan: '+(e.message||e))}finally{setBusy(false)}}
 const resetAll=async()=>{if(!activeUnit)return;const total=data.bank.length+data.settlements.length+data.redemptions.length;if(!total)return;const ok=window.confirm(`RESET SEMUA DATA ${activeUnit.name}? Rekening koran, setoran, dan tebusan (${total} baris) akan dihapus. Tindakan ini tidak dapat dibatalkan.`);if(!ok)return;try{setBusy(true);await resetUnitData(activeUnit.id);await reload();setNotice('Semua data transaksi unit ini sudah direset.')}catch(e:any){setNotice('Gagal reset data: '+(e.message||e))}finally{setBusy(false)}}
 const saveEdit=async(tx:BankTx)=>{try{setBusy(true);await updateInternalNote(tx.id,tx.internalNote||'');setData(d=>({...d,bank:d.bank.map(x=>x.id===tx.id?{...x,internalNote:tx.internalNote}:x)}));setEditing(null);setNotice('Keterangan internal tersimpan.')}catch(e:any){setNotice('Gagal menyimpan: '+e.message)}finally{setBusy(false)}}
 const download=()=>{const blob=new Blob(['\ufeff'+toCSV(filtered)],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`rekening-koran-${activeUnit?.name||'unit'}${dateFrom||dateTo?`-${dateFrom||'awal'}-${dateTo||'akhir'}`:''}.csv`;a.click();URL.revokeObjectURL(a.href)}
 const switchType=(type:UnitType)=>{const u=units.find(x=>x.unitType===type);if(u)setActiveUnit(u)}
 const newUnit=async()=>{const name=window.prompt('Nama unit/perusahaan baru');if(!name)return;const type=(window.prompt('Jenis unit: SPBU / LPG / SPPBE / OTHER','SPBU')||'SPBU').toUpperCase() as UnitType;if(!['SPBU','LPG','SPPBE','OTHER'].includes(type)){setNotice('Jenis unit tidak valid.');return}try{setBusy(true);const u=await addUnit(name,type);setUnits(x=>[...x,u]);setActiveUnit(u)}catch(e:any){setNotice(e.message)}finally{setBusy(false)}}
 const FileBox=({kind,title,desc,icon}:{kind:'bank'|'settlement'|'redemption',title:string,desc:string,icon:React.ReactNode})=><label className="filebox">{icon}<div><b>{title}</b><span>{desc}</span></div><input type="file" accept=".xlsx,.xls,.csv" disabled={busy} onChange={e=>handle(kind,e.target.files?.[0])}/><span className="pill">Pilih file</span></label>

 const openPaste=(kind:'bank'|'settlement'|'redemption')=>{setPasteKind(kind);setPasteText('');setPastePreview(null);setReplacePaste(kind==='bank'?replaceBank:false)}
 const previewPaste=()=>{if(!pasteKind)return;const result=pasteKind==='bank'?parsePastedBank(pasteText,pasteYear,pasteMonth):pasteKind==='settlement'?parsePastedSettlements(pasteText,pasteYear,pasteMonth):parsePastedRedemptions(pasteText,pasteYear,pasteMonth);setPastePreview(result)}
 const savePaste=async()=>{if(!pasteKind||!activeUnit||!pastePreview?.rows?.length)return;try{setBusy(true);if(replacePaste){if(pasteKind==='bank')await deleteBankData(activeUnit.id);else if(pasteKind==='settlement')await deleteSettlementData(activeUnit.id);else await deleteRedemptionData(activeUnit.id)}const label=pasteKind==='bank'?'rekening':pasteKind==='settlement'?'setoran':'tebusan';const f=new File([pasteText],`paste-${label}-${Date.now()}.tsv`,{type:'text/tab-separated-values'});const b=await createBatch(activeUnit.id,pasteKind,f,pastePreview.rows.length);if(pasteKind==='bank')await insertBank(activeUnit.id,b,pastePreview.rows);else if(pasteKind==='settlement')await insertSettlements(activeUnit.id,b,pastePreview.rows);else await insertRedemptions(activeUnit.id,b,pastePreview.rows);await reload();setNotice(`${pastePreview.rows.length} baris ${label} hasil copy-paste disimpan${replacePaste?' dan menggantikan data lama':''}.`);setPasteKind(null);setPastePreview(null);setPasteText('')}catch(e:any){setNotice('Gagal menyimpan hasil paste: '+(e.message||e))}finally{setBusy(false)}}

 if(!supabaseConfigured)return <CenterMessage title="Konfigurasi Supabase belum ada" text="Isi NEXT_PUBLIC_SUPABASE_URL dan NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY."/>
 if(authLoading)return <CenterMessage title="Membuka RK Analyzer" text="Memeriksa sesi login..." loading/>
 if(!session)return <AuthScreen/>
 return <main className="appShell">
  <aside className="sidebar"><div className="brand"><div className="logo">RK</div><div><b>RK Analyzer</b><small>SPBU & LPG</small></div></div>
   <nav>{[['dashboard',<LayoutDashboard key="a"/>, 'Dashboard'],['bank',<Landmark key="b"/>,'Rekening Koran'],['setoran',<Upload key="c"/>,'Data Setoran'],['tebusan',<Fuel key="d"/>,'Data Tebusan'],['rekon',<RefreshCw key="e"/>,'Rekonsiliasi']].map(([id,ic,label]:any)=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{ic}{label}</button>)}</nav>
   <div className="sideFoot"><Database size={16}/><span>Supabase Online<br/><small>Data tersimpan di cloud</small></span></div>
  </aside>
  <section className="content">
   <header><div><h1>{tab==='dashboard'?'Dashboard Rekonsiliasi':tab==='bank'?'Rekening Koran':tab==='setoran'?'Tabel Setoran':tab==='tebusan'?'Tabel Tebusan':'Rekonsiliasi Transaksi'}</h1><p>{activeUnit?.name||'Pilih unit'} • pemberian keterangan otomatis & pemeriksaan silang</p></div><div className="headTools"><div className="unitPick"><button className={activeUnit?.unitType==='SPBU'?'on':''} onClick={()=>switchType('SPBU')}><Fuel/>SPBU</button><button className={activeUnit?.unitType==='LPG'?'on':''} onClick={()=>switchType('LPG')}><Flame/>LPG</button></div><select className="unitSelect" value={activeUnit?.id||''} onChange={e=>setActiveUnit(units.find(x=>x.id===e.target.value)||null)}>{units.map(u=><option key={u.id} value={u.id}>{u.name} ({u.unitType})</option>)}</select><button className="headBtn" onClick={newUnit} title="Tambah unit"><Plus/></button><button className="headBtn" onClick={()=>supabase.auth.signOut()} title="Keluar"><LogOut/></button></div></header>
   <DateFilter from={dateFrom} to={dateTo} setFrom={setDateFrom} setTo={setDateTo} shown={ranged.length} total={analyzed.length}/>
   {notice&&<div className="notice">{busy&&<LoaderCircle className="spin"/>}{notice}<button onClick={()=>setNotice('')}>×</button></div>}

   {tab==='dashboard'&&<><div className="cards"><Card t="Dana Masuk" v={rupiah(incoming)} s={`${ranged.filter(x=>x.credit>0).length} transaksi`}/><Card t="Dana Keluar" v={rupiah(outgoing)} s={`${ranged.filter(x=>x.debit>0).length} transaksi`}/><Card t="Cocok Otomatis" v={`${counts.matched}`} s="transaksi" good/><Card t="Perlu Diperiksa" v={`${counts.review+counts.unmatched}`} s="transaksi" warn/></div>
    <section className="panel"><div className="panelHead"><div><h2>Masukkan Data Pembanding</h2><p>Upload file atau copy-paste dari Excel pada unit yang sedang dipilih.</p></div><div className="dataTools"><label className="replaceToggle"><input type="checkbox" checked={replaceBank} onChange={e=>setReplaceBank(e.target.checked)}/><span>Ganti rekening lama saat upload/paste</span></label><button className="softBtn" onClick={()=>openPaste('bank')}><ClipboardPaste/>Paste Rekening</button><button className="softBtn" onClick={()=>openPaste('settlement')}><ClipboardPaste/>Paste Setoran</button><button className="softBtn" onClick={()=>openPaste('redemption')}><ClipboardPaste/>Paste Tebusan</button><button className="dangerGhost" disabled={busy||!data.bank.length} onClick={clearBank}><Trash2/>Hapus Rekening</button><button className="dangerGhost" disabled={busy||!(data.bank.length+data.settlements.length+data.redemptions.length)} onClick={resetAll}><RotateCcw/>Reset Unit</button></div></div><div className="uploadGrid"><FileBox kind="bank" title="Rekening Koran" desc={replaceBank?'Upload/paste baru dapat mengganti rekening lama':'File baru akan ditambahkan ke data lama'} icon={<Landmark/>}/><FileBox kind="settlement" title="Tabel Setoran" desc="Upload Excel/CSV atau gunakan Paste Setoran" icon={<FileSpreadsheet/>}/><FileBox kind="redemption" title="Tabel Tebusan" desc="Upload Excel/CSV atau gunakan Paste Tebusan" icon={<Fuel/>}/></div></section>
    <section className="panel"><div className="panelHead"><h2>Status Rekonsiliasi</h2></div><div className="statusLine"><Status icon={<CheckCircle2/>} label="Cocok" n={counts.matched}/><Status icon={<AlertTriangle/>} label="Perlu cek" n={counts.review}/><Status icon={<XCircle/>} label="Belum cocok" n={counts.unmatched}/></div></section></>}

   {tab==='setoran'&&<DataTable title="Data setoran pembanding" sub={`${rangedSettlements.length} dari ${data.settlements.length} baris`} actions={<><button className="softBtn" onClick={()=>openPaste('settlement')}><ClipboardPaste/>Paste dari Excel</button><button className="dangerAction" disabled={busy||!data.settlements.length} onClick={clearSetoran}><Trash2/>Hapus Setoran</button></>} rows={rangedSettlements.map(x=>[fmtDate(x.date),x.label,rupiah(x.total),x.source||'-'])} heads={['Tanggal','Keterangan','Total','Sumber']}/>} 
   {tab==='tebusan'&&<DataTable title="Data tebusan pembanding" sub={`${rangedRedemptions.length} dari ${data.redemptions.length} baris`} actions={<><button className="softBtn" onClick={()=>openPaste('redemption')}><ClipboardPaste/>Paste dari Excel</button><button className="dangerAction" disabled={busy||!data.redemptions.length} onClick={clearTebusan}><Trash2/>Hapus Tebusan</button></>} rows={rangedRedemptions.map(x=>[fmtDate(x.date),x.product,`${x.qty||'-'} ${x.unit}`,rupiah(x.total),x.doNo||'-',x.source||'-'])} heads={['Tanggal','Produk','Qty/Volume','Total','DO/LO','Sumber']}/>} 
   {(tab==='bank'||tab==='rekon')&&<section className="panel wide"><div className="panelHead"><div><h2>{tab==='bank'?'Mutasi Rekening + Keterangan':'Hasil Pencocokan'}</h2><p>{ranged.length} dari {analyzed.length} transaksi dalam periode filter</p></div><div className="actions"><div className="search"><Search/><input placeholder="Cari transaksi..." value={query} onChange={e=>setQuery(e.target.value)}/></div>{tab==='bank'&&<button className="softBtn" onClick={()=>openPaste('bank')}><ClipboardPaste/>Paste dari Excel</button>}{tab==='bank'&&<button className="dangerAction" disabled={busy||!data.bank.length} onClick={clearBank}><Trash2/>Hapus</button>}<button onClick={download}><Download/>CSV</button><button onClick={()=>window.print()}><Printer/>Cetak</button></div></div>
    <div className="tableWrap"><table><thead><tr><th>Tanggal</th><th>Uraian Bank</th><th>Debit</th><th>Kredit</th><th>Kategori</th><th>Keterangan Internal</th><th>Status</th><th>Dasar</th><th></th></tr></thead><tbody>{filtered.map(tx=><tr key={tx.id}><td>{fmtDate(tx.date)}</td><td className="desc">{tx.description||'-'}</td><td className="money">{tx.debit?rupiah(tx.debit):'-'}</td><td className="money">{tx.credit?rupiah(tx.credit):'-'}</td><td>{tx.category}</td><td><b>{tx.internalNote}</b>{tx.difference? <small className="diff">Selisih {rupiah(tx.difference)}</small>:null}</td><td><span className={`badge ${tx.matchStatus}`}>{statusLabel[tx.matchStatus||'unmatched']} • {tx.confidence}%</span></td><td><small>{tx.matchSource}</small></td><td><button className="iconBtn" onClick={()=>setEditing(tx)}><Pencil/></button></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty">Tidak ada transaksi pada filter ini.</div>}</div></section>}
  </section>

  {editing&&<div className="modalBack" onClick={()=>setEditing(null)}><div className="modal" onClick={e=>e.stopPropagation()}><h3>Edit Keterangan Internal</h3><p className="muted">Keterangan bank asli tetap disimpan dan tidak berubah.</p><div className="bankOrig">{editing.description}</div><textarea rows={5} value={editing.internalNote||''} onChange={e=>setEditing({...editing,internalNote:e.target.value})}/><div className="modalActions"><button onClick={()=>setEditing(null)}>Batal</button><button className="primary" onClick={()=>saveEdit(editing)}>Simpan Koreksi</button></div></div></div>}
  {pasteKind&&<PasteModal kind={pasteKind} text={pasteText} setText={v=>{setPasteText(v);setPastePreview(null)}} month={pasteMonth} setMonth={setPasteMonth} year={pasteYear} setYear={setPasteYear} preview={pastePreview} onPreview={previewPaste} onClose={()=>setPasteKind(null)} onSave={savePaste} replace={replacePaste} setReplace={setReplacePaste} busy={busy}/>} 
 </main>
}

function DateFilter({from,to,setFrom,setTo,shown,total}:{from:string,to:string,setFrom:(v:string)=>void,setTo:(v:string)=>void,shown:number,total:number}){
 return <div className="dateFilter"><b>Filter tanggal</b><label>Dari<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Sampai<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button onClick={()=>{setFrom('');setTo('')}} disabled={!from&&!to}>Semua Tanggal</button><span>{shown} / {total} transaksi</span></div>
}

function PasteModal({kind,text,setText,month,setMonth,year,setYear,preview,onPreview,onClose,onSave,replace,setReplace,busy}:{kind:'bank'|'settlement'|'redemption',text:string,setText:(v:string)=>void,month:number,setMonth:(v:number)=>void,year:number,setYear:(v:number)=>void,preview:any,onPreview:()=>void,onClose:()=>void,onSave:()=>void,replace:boolean,setReplace:(v:boolean)=>void,busy:boolean}){
 const isBank=kind==='bank',isSetoran=kind==='settlement',label=isBank?'Rekening Koran':isSetoran?'Data Setoran':'Data Tebusan',sample=(preview?.rows||[]).slice(0,8)
 return <div className="modalBack" onClick={onClose}><div className="modal pasteModal" onClick={e=>e.stopPropagation()}><div className="pasteTitle"><div><h3>Copy-Paste {label}</h3><p className="muted">Blok tabel di Excel → Copy → Paste di bawah. Sertakan baris judul kolom.</p></div><button className="closeBtn" onClick={onClose}>×</button></div>
  <div className="pastePeriod"><label>Bulan<select value={month} onChange={e=>{setMonth(Number(e.target.value));setText(text)}}>{months.map((m,i)=><option key={m} value={i+1}>{m}</option>)}</select></label><label>Tahun<input type="number" min="2020" max="2100" value={year} onChange={e=>{setYear(Number(e.target.value));setText(text)}}/></label><small>{isBank?'Dipakai hanya jika kolom tanggal yang ditempel berupa angka 1–31.':'Dipakai bila kolom tanggal hanya berisi angka 1–31.'}</small></div>
  <textarea className="pasteArea" rows={10} value={text} onChange={e=>setText(e.target.value)} placeholder={isBank?'Paste rekening koran di sini, termasuk header Date & Time / Tanggal, Description, Debit, Credit, Balance...':isSetoran?'Paste rekap setoran / Report Order di sini...':'Paste rekap tebusan di sini...'}/>
  <div className="pasteActions"><label className="replaceToggle"><input type="checkbox" checked={replace} onChange={e=>setReplace(e.target.checked)}/><span>Ganti seluruh data {isBank?'rekening koran':isSetoran?'setoran':'tebusan'} lama saat simpan</span></label><button onClick={onPreview} disabled={!text.trim()||busy}>Preview Data</button></div>
  {preview&&<div className="previewBox"><div className={`previewStats ${isBank?'bankPreviewStats':''}`}><div><span>Format dikenali</span><b>{preview.format}</b></div><div><span>Baris valid</span><b>{preview.rows.length}</b></div><div><span>Diabaikan</span><b>{preview.ignored}</b></div>{isBank?<><div><span>Total Debit</span><b>{rupiah(preview.debitTotal||0)}</b></div><div><span>Total Kredit</span><b>{rupiah(preview.creditTotal||0)}</b></div></>:<div><span>Total nominal</span><b>{rupiah(preview.total)}</b></div>}</div>{isBank&&(preview.dateFrom||preview.dateTo)&&<div className="previewPeriod">Periode terbaca: <b>{preview.dateFrom||'-'}</b> s/d <b>{preview.dateTo||'-'}</b></div>}{preview.warnings?.map((w:string,i:number)=><div className="previewWarn" key={i}>{w}</div>)}
   <div className="miniTable"><table><thead><tr>{isBank?<><th>Tanggal</th><th>Uraian</th><th>Debit</th><th>Kredit</th><th>Saldo</th></>:isSetoran?<><th>Tanggal</th><th>Keterangan</th><th>Total</th></>:<><th>Tanggal</th><th>Produk</th><th>Qty</th><th>Total</th></>}</tr></thead><tbody>{sample.map((r:any,i:number)=><tr key={i}>{isBank?<><td>{fmtDate(r.date)}</td><td>{r.description||'-'}</td><td>{r.debit?rupiah(r.debit):'-'}</td><td>{r.credit?rupiah(r.credit):'-'}</td><td>{r.balance?rupiah(r.balance):'-'}</td></>:isSetoran?<><td>{fmtDate(r.date)}</td><td>{r.label}</td><td>{rupiah(r.total)}</td></>:<><td>{fmtDate(r.date)}</td><td>{r.product}</td><td>{r.qty} {r.unit}</td><td>{rupiah(r.total)}</td></>}</tr>)}</tbody></table></div>
  </div>}
  <div className="modalActions"><button onClick={onClose}>Batal</button><button className="primary" disabled={busy||!preview?.rows?.length} onClick={onSave}>{busy?'Menyimpan...':`Simpan ${preview?.rows?.length||0} Baris`}</button></div>
 </div></div>
}
function AuthScreen(){const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[mode,setMode]=useState<'login'|'signup'>('login'),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);const go=async()=>{try{setBusy(true);setMsg('');if(mode==='login'){const{error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error}else{const{data,error}=await supabase.auth.signUp({email,password});if(error)throw error;setMsg(data.session?'Akun dibuat dan sudah masuk.':'Akun dibuat. Jika diminta, cek email untuk konfirmasi lalu login.')}}catch(e:any){setMsg(e.message||'Gagal login')}finally{setBusy(false)}};return <div className="authPage"><div className="authCard"><div className="authLogo">RK</div><h1>RK Analyzer</h1><p>Rekening koran, setoran, dan tebusan SPBU/LPG dalam satu rekonsiliasi.</p><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="nama@email.com"/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Minimal 6 karakter" onKeyDown={e=>e.key==='Enter'&&go()}/></label>{msg&&<div className="authMsg">{msg}</div>}<button className="authPrimary" disabled={busy||!email||password.length<6} onClick={go}>{busy?'Memproses...':mode==='login'?'Masuk':'Buat Akun'}</button><button className="authSwitch" onClick={()=>setMode(mode==='login'?'signup':'login')}>{mode==='login'?'Belum punya akun? Buat akun':'Sudah punya akun? Masuk'}</button></div></div>}
function CenterMessage({title,text,loading}:{title:string,text:string,loading?:boolean}){return <div className="authPage"><div className="authCard center">{loading&&<LoaderCircle className="spin big"/>}<h1>{title}</h1><p>{text}</p></div></div>}
function Card({t,v,s,good,warn}:{t:string,v:string,s:string,good?:boolean,warn?:boolean}){return <div className={`card ${good?'good':''} ${warn?'warn':''}`}><span>{t}</span><strong>{v}</strong><small>{s}</small></div>}
function Status({icon,label,n}:{icon:React.ReactNode,label:string,n:number}){return <div className="statusItem">{icon}<div><b>{n}</b><span>{label}</span></div></div>}
function DataTable({title,sub,heads,rows,actions}:{title:string,sub?:string,heads:string[],rows:any[][],actions?:React.ReactNode}){return <section className="panel"><div className="panelHead"><div><h2>{title}</h2>{sub&&<p>{sub}</p>}</div>{actions&&<div className="actions">{actions}</div>}</div><div className="tableWrap"><table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table>{!rows.length&&<div className="empty">Belum ada data pada periode ini.</div>}</div></section>}
