'use client'
import { useEffect, useMemo, useState } from 'react'
import type { Session } from '@supabase/supabase-js'
import { Upload, Landmark, Fuel, Flame, Search, CheckCircle2, AlertTriangle, XCircle, Pencil, FileSpreadsheet, Download, Printer, Database, LayoutDashboard, RefreshCw, LogOut, Plus, LoaderCircle } from 'lucide-react'
import { AppData, BankTx, UnitType } from '@/lib/types'
import { classify, fmtDate, parseBank, parseRedemptions, parseSettlements, rupiah, toCSV } from '@/lib/utils'
import { supabase, supabaseConfigured } from '@/lib/supabase'
import { addUnit, bootstrapUnits, createBatch, insertBank, insertRedemptions, insertSettlements, loadUnitData, RkUnit, updateInternalNote } from '@/lib/db'

const initial:AppData={bank:[],settlements:[],redemptions:[],unitType:'SPBU',unitName:'SPBU Utama'}
const statusLabel:any={matched:'Cocok',partial:'Ada selisih',review:'Perlu cek',unmatched:'Belum cocok'}

export default function Home(){
 const [session,setSession]=useState<Session|null>(null),[authLoading,setAuthLoading]=useState(true)
 const [units,setUnits]=useState<RkUnit[]>([]),[activeUnit,setActiveUnit]=useState<RkUnit|null>(null)
 const [data,setData]=useState<AppData>(initial), [tab,setTab]=useState('dashboard'), [query,setQuery]=useState(''), [editing,setEditing]=useState<BankTx|null>(null)
 const [busy,setBusy]=useState(false),[notice,setNotice]=useState('')
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setAuthLoading(false)});const {data:s}=supabase.auth.onAuthStateChange((_e,sess)=>{setSession(sess);setAuthLoading(false)});return()=>s.subscription.unsubscribe()},[])
 useEffect(()=>{if(!session)return; (async()=>{try{setBusy(true);const u=await bootstrapUnits();setUnits(u);setActiveUnit(x=>x&&u.find(z=>z.id===x.id)||u[0]||null)}catch(e:any){setNotice(e.message||'Gagal memuat unit')}finally{setBusy(false)}})()},[session])
 useEffect(()=>{if(!activeUnit)return;(async()=>{try{setBusy(true);const d=await loadUnitData(activeUnit.id);setData({...d,unitId:activeUnit.id,unitType:activeUnit.unitType,unitName:activeUnit.name})}catch(e:any){setNotice(e.message||'Gagal memuat data')}finally{setBusy(false)}})()},[activeUnit])
 const analyzed=useMemo(()=>classify(data.bank,data.settlements,data.redemptions),[data.bank,data.settlements,data.redemptions])
 const filtered=analyzed.filter(x=>(x.description+' '+x.internalNote+' '+x.category).toLowerCase().includes(query.toLowerCase()))
 const counts={matched:analyzed.filter(x=>x.matchStatus==='matched').length, review:analyzed.filter(x=>x.matchStatus==='review'||x.matchStatus==='partial').length, unmatched:analyzed.filter(x=>x.matchStatus==='unmatched').length}
 const incoming=analyzed.reduce((a,b)=>a+b.credit,0), outgoing=analyzed.reduce((a,b)=>a+b.debit,0)
 const reload=async()=>{if(!activeUnit)return;const d=await loadUnitData(activeUnit.id);setData({...d,unitId:activeUnit.id,unitType:activeUnit.unitType,unitName:activeUnit.name})}
 const handle=async(kind:'bank'|'settlement'|'redemption',f?:File)=>{if(!f||!activeUnit)return;try{setBusy(true);setNotice(`Membaca ${f.name}...`);if(kind==='bank'){const rows=await parseBank(f);const b=await createBatch(activeUnit.id,kind,f,rows.length);await insertBank(activeUnit.id,b,rows);setNotice(`${rows.length} baris rekening koran diproses.`)}if(kind==='settlement'){const rows=await parseSettlements(f);const b=await createBatch(activeUnit.id,kind,f,rows.length);await insertSettlements(activeUnit.id,b,rows);setNotice(`${rows.length} baris setoran disimpan.`)}if(kind==='redemption'){const rows=await parseRedemptions(f);const b=await createBatch(activeUnit.id,kind,f,rows.length);await insertRedemptions(activeUnit.id,b,rows);setNotice(`${rows.length} baris tebusan disimpan.`)}await reload()}catch(e:any){setNotice('Gagal upload: '+(e.message||e))}finally{setBusy(false)}}
 const saveEdit=async(tx:BankTx)=>{try{setBusy(true);await updateInternalNote(tx.id,tx.internalNote||'');setData(d=>({...d,bank:d.bank.map(x=>x.id===tx.id?{...x,internalNote:tx.internalNote}:x)}));setEditing(null);setNotice('Keterangan internal tersimpan.')}catch(e:any){setNotice('Gagal menyimpan: '+e.message)}finally{setBusy(false)}}
 const download=()=>{const blob=new Blob(['\ufeff'+toCSV(analyzed)],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`rekening-koran-${activeUnit?.name||'unit'}.csv`;a.click();URL.revokeObjectURL(a.href)}
 const switchType=(type:UnitType)=>{const u=units.find(x=>x.unitType===type);if(u)setActiveUnit(u)}
 const newUnit=async()=>{const name=window.prompt('Nama unit/perusahaan baru');if(!name)return;const type=(window.prompt('Jenis unit: SPBU / LPG / SPPBE / OTHER','SPBU')||'SPBU').toUpperCase() as UnitType;if(!['SPBU','LPG','SPPBE','OTHER'].includes(type)){setNotice('Jenis unit tidak valid.');return}try{setBusy(true);const u=await addUnit(name,type);setUnits(x=>[...x,u]);setActiveUnit(u)}catch(e:any){setNotice(e.message)}finally{setBusy(false)}}
 const FileBox=({kind,title,desc,icon}:{kind:'bank'|'settlement'|'redemption',title:string,desc:string,icon:React.ReactNode})=><label className="filebox">{icon}<div><b>{title}</b><span>{desc}</span></div><input type="file" accept=".xlsx,.xls,.csv" disabled={busy} onChange={e=>handle(kind,e.target.files?.[0])}/><span className="pill">Pilih file</span></label>
 if(!supabaseConfigured)return <CenterMessage title="Konfigurasi Supabase belum ada" text="Isi NEXT_PUBLIC_SUPABASE_URL dan NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY."/>
 if(authLoading)return <CenterMessage title="Membuka RK Analyzer" text="Memeriksa sesi login..." loading/>
 if(!session)return <AuthScreen/>
 return <main className="appShell">
  <aside className="sidebar"><div className="brand"><div className="logo">RK</div><div><b>RK Analyzer</b><small>SPBU & LPG</small></div></div>
   <nav>{[['dashboard',<LayoutDashboard key="a"/>, 'Dashboard'],['bank',<Landmark key="b"/>,'Rekening Koran'],['setoran',<Upload key="c"/>,'Data Setoran'],['tebusan',<Fuel key="d"/>,'Data Tebusan'],['rekon',<RefreshCw key="e"/>,'Rekonsiliasi']].map(([id,ic,label]:any)=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{ic}{label}</button>)}</nav>
   <div className="sideFoot"><Database size={16}/><span>Supabase Online<br/><small>Data tersimpan di cloud</small></span></div>
  </aside>
  <section className="content">
   <header><div><h1>{tab==='dashboard'?'Dashboard Rekonsiliasi':tab==='bank'?'Rekening Koran':tab==='setoran'?'Tabel Setoran':tab==='tebusan'?'Tabel Tebusan':'Rekonsiliasi Transaksi'}</h1><p>{activeUnit?.name||'Pilih unit'} • pemberian keterangan otomatis & pemeriksaan silang</p></div><div className="headTools"><div className="unitPick"><button className={activeUnit?.unitType==='SPBU'?'on':''} onClick={()=>switchType('SPBU')}><Fuel/>SPBU</button><button className={activeUnit?.unitType==='LPG'?'on':''} onClick={()=>switchType('LPG')}><Flame/>LPG</button></div><select className="unitSelect" value={activeUnit?.id||''} onChange={e=>setActiveUnit(units.find(x=>x.id===e.target.value)||null)}>{units.map(u=><option key={u.id} value={u.id}>{u.name} ({u.unitType})</option>)}</select><button className="headBtn" onClick={newUnit} title="Tambah unit"><Plus/></button><button className="headBtn" onClick={()=>supabase.auth.signOut()} title="Keluar"><LogOut/></button></div></header>
   {notice&&<div className="notice">{busy&&<LoaderCircle className="spin"/>}{notice}<button onClick={()=>setNotice('')}>×</button></div>}
   {tab==='dashboard'&&<><div className="cards"><Card t="Dana Masuk" v={rupiah(incoming)} s={`${analyzed.filter(x=>x.credit>0).length} transaksi`}/><Card t="Dana Keluar" v={rupiah(outgoing)} s={`${analyzed.filter(x=>x.debit>0).length} transaksi`}/><Card t="Cocok Otomatis" v={`${counts.matched}`} s="transaksi" good/><Card t="Perlu Diperiksa" v={`${counts.review+counts.unmatched}`} s="transaksi" warn/></div>
    <section className="panel"><div className="panelHead"><div><h2>Masukkan Data Pembanding</h2><p>Upload rekening koran, setoran, dan tebusan pada unit yang sedang dipilih.</p></div></div><div className="uploadGrid"><FileBox kind="bank" title="Rekening Koran" desc="Excel/CSV hasil download bank" icon={<Landmark/>}/><FileBox kind="settlement" title="Tabel Setoran" desc="Setoran penjualan, sales, QRIS, pelanggan" icon={<FileSpreadsheet/>}/><FileBox kind="redemption" title="Tabel Tebusan" desc={activeUnit?.unitType==='SPBU'?'Pertalite, Pertamax, Bio Solar, Dexlite, Pertamina Dex':'LPG 3 Kg, 5,5 Kg, 12 Kg, 50 Kg'} icon={<Fuel/>}/></div></section>
    <section className="panel"><div className="panelHead"><h2>Status Rekonsiliasi</h2></div><div className="statusLine"><Status icon={<CheckCircle2/>} label="Cocok" n={counts.matched}/><Status icon={<AlertTriangle/>} label="Perlu cek" n={counts.review}/><Status icon={<XCircle/>} label="Belum cocok" n={counts.unmatched}/></div></section></>}
   {tab==='setoran'&&<DataTable title="Data setoran pembanding" rows={data.settlements.map(x=>[fmtDate(x.date),x.label,rupiah(x.total),x.source||'-'])} heads={['Tanggal','Keterangan','Total','Sumber']}/>} 
   {tab==='tebusan'&&<DataTable title="Data tebusan pembanding" rows={data.redemptions.map(x=>[fmtDate(x.date),x.product,`${x.qty||'-'} ${x.unit}`,rupiah(x.total),x.doNo||'-',x.source||'-'])} heads={['Tanggal','Produk','Qty/Volume','Total','DO/LO','Sumber']}/>} 
   {(tab==='bank'||tab==='rekon')&&<section className="panel wide"><div className="panelHead"><div><h2>{tab==='bank'?'Mutasi Rekening + Keterangan':'Hasil Pencocokan'}</h2><p>{analyzed.length} transaksi dianalisis</p></div><div className="actions"><div className="search"><Search/><input placeholder="Cari transaksi..." value={query} onChange={e=>setQuery(e.target.value)}/></div><button onClick={download}><Download/>CSV</button><button onClick={()=>window.print()}><Printer/>Cetak</button></div></div>
    <div className="tableWrap"><table><thead><tr><th>Tanggal</th><th>Uraian Bank</th><th>Debit</th><th>Kredit</th><th>Kategori</th><th>Keterangan Internal</th><th>Status</th><th>Dasar</th><th></th></tr></thead><tbody>{filtered.map(tx=><tr key={tx.id}><td>{fmtDate(tx.date)}</td><td className="desc">{tx.description||'-'}</td><td className="money">{tx.debit?rupiah(tx.debit):'-'}</td><td className="money">{tx.credit?rupiah(tx.credit):'-'}</td><td>{tx.category}</td><td><b>{tx.internalNote}</b>{tx.difference? <small className="diff">Selisih {rupiah(tx.difference)}</small>:null}</td><td><span className={`badge ${tx.matchStatus}`}>{statusLabel[tx.matchStatus||'unmatched']} • {tx.confidence}%</span></td><td><small>{tx.matchSource}</small></td><td><button className="iconBtn" onClick={()=>setEditing(tx)}><Pencil/></button></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty">Belum ada transaksi. Upload rekening koran terlebih dahulu.</div>}</div></section>}
  </section>
  {editing&&<div className="modalBack" onClick={()=>setEditing(null)}><div className="modal" onClick={e=>e.stopPropagation()}><h3>Edit Keterangan Internal</h3><p className="muted">Keterangan bank asli tetap disimpan dan tidak berubah.</p><div className="bankOrig">{editing.description}</div><textarea rows={5} value={editing.internalNote||''} onChange={e=>setEditing({...editing,internalNote:e.target.value})}/><div className="modalActions"><button onClick={()=>setEditing(null)}>Batal</button><button className="primary" onClick={()=>saveEdit(editing)}>Simpan Koreksi</button></div></div></div>}
 </main>
}

function AuthScreen(){const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[mode,setMode]=useState<'login'|'signup'>('login'),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);const go=async()=>{try{setBusy(true);setMsg('');if(mode==='login'){const{error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error}else{const{data,error}=await supabase.auth.signUp({email,password});if(error)throw error;setMsg(data.session?'Akun dibuat dan sudah masuk.':'Akun dibuat. Jika diminta, cek email untuk konfirmasi lalu login.')}}catch(e:any){setMsg(e.message||'Gagal login')}finally{setBusy(false)}};return <div className="authPage"><div className="authCard"><div className="authLogo">RK</div><h1>RK Analyzer</h1><p>Rekening koran, setoran, dan tebusan SPBU/LPG dalam satu rekonsiliasi.</p><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="nama@email.com"/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Minimal 6 karakter" onKeyDown={e=>e.key==='Enter'&&go()}/></label>{msg&&<div className="authMsg">{msg}</div>}<button className="authPrimary" disabled={busy||!email||password.length<6} onClick={go}>{busy?'Memproses...':mode==='login'?'Masuk':'Buat Akun'}</button><button className="authSwitch" onClick={()=>setMode(mode==='login'?'signup':'login')}>{mode==='login'?'Belum punya akun? Buat akun':'Sudah punya akun? Masuk'}</button></div></div>}
function CenterMessage({title,text,loading}:{title:string,text:string,loading?:boolean}){return <div className="authPage"><div className="authCard center">{loading&&<LoaderCircle className="spin big"/>}<h1>{title}</h1><p>{text}</p></div></div>}
function Card({t,v,s,good,warn}:{t:string,v:string,s:string,good?:boolean,warn?:boolean}){return <div className={`card ${good?'good':''} ${warn?'warn':''}`}><span>{t}</span><strong>{v}</strong><small>{s}</small></div>}
function Status({icon,label,n}:{icon:React.ReactNode,label:string,n:number}){return <div className="statusItem">{icon}<div><b>{n}</b><span>{label}</span></div></div>}
function DataTable({title,heads,rows}:{title:string,heads:string[],rows:any[][]}){return <section className="panel"><div className="panelHead"><h2>{title}</h2></div><div className="tableWrap"><table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table>{!rows.length&&<div className="empty">Belum ada data. Gunakan halaman Dashboard untuk upload file.</div>}</div></section>}
